---
extends: eslint:recommended

parserOptions:
    exmaVersion: 6
    sourceType: module
    ecmaFeatures:
        jsx: true
        restParams: true
        spread: true
        experimentalObjectRestSpread: true
env:
    browser: true
    es6: true
    node: true
rules:
    # Possible Errors
    comma-dangle:
        - 2
        - always-multiline
    no-console: 1
    no-unexpected-multiline: 2
    valid-jsdoc:
        - 2
        - requireReturn: false

    # Best Practices
    array-callback-return: 2
    consistent-return: 0
    block-scoped-var: 2
    curly:
        - 2
        - multi-line
    dot-location:
        - 2
        - property
    dot-notation: 2
    eqeqeq:
        - 2
        - smart
    guard-for-in: 2
    no-alert: 1
    no-caller: 2
    no-case-declarations: 2
    no-div-regex: 2
    no-else-return: 2
    no-empty-function:
        - 2
        - allow:
            - arrowFunctions
    no-eval: 1
    no-extend-native: 2
    no-extra-bind: 2
    no-extra-label: 2
    no-floating-decimal: 2
    no-implicit-globals: 2
    no-implied-eval: 2
    no-invalid-this: 0
    no-iterator: 2
    no-labels: 2
    no-lone-blocks: 2
    no-loop-func: 2
    no-magic-numbers: 0
    no-multi-str: 2
    no-native-reassign: 2
    no-new-func: 2
    no-new-wrappers: 2
    no-new: 2
    no-octal-escape: 2
    no-param-reassign: 2
    no-proto: 2
    no-return-assign: 2
    no-script-url: 2
    no-self-compare: 2
    no-sequences: 2
    no-throw-literal: 2
    no-unmodified-loop-condition: 2
    no-unused-expressions: 2
    no-useless-call: 2
    no-useless-concat: 2
    no-void: 2
    no-warning-comments: 1
    no-with: 2
    radix: 2
    vars-on-top: 2
    wrap-iife: 2
    yoda: 2

    # Strict Mode
    strict: 2

    # Variables
    init-declarations: 0
    no-catch-shadow: 2
    no-label-var: 2
    no-shadow-restricted-names: 2
    no-shadow: 0
    no-undef-init: 2
    no-unused-vars:
        - 0 # Want to use, but does not parses in JSX
        - varsIgnorePattern: React
    no-use-before-define: 2

    # Node.js and CommonJS
    callback-return: 2
    global-require: 1
    handle-callback-err: 2
    no-mixed-requires: 2
    no-new-require: 2
    no-path-concat: 2
    no-process-exit: 2
    no-sync: 2

    # Stylistic Issues
    brace-style: 2
    comma-style: 2
    consistent-this: 2
    jsx-quotes: 2
    key-spacing: 2
    keyword-spacing: 2
    lines-around-comment: 2
    max-depth: 2
    max-len:
        - 2
        - 80
        - 4
        - ignorePattern: "^\\s*[`'].*[`'][;,]?$"
    max-nested-callbacks: 
        - 2
        - 3
    max-params: 2
    max-statements: 1
    new-cap: 0
    new-parens: 2
    newline-after-var: 0
    newline-per-chained-call:
        - 2
        - ignoreChainWithDepth: 4
    no-array-constructor: 2
    no-continue: 2
    no-inline-comments: 2
    no-lonely-if : 2
    no-multiple-empty-lines: 2
    no-nested-ternary: 2
    no-new-object: 2
    no-restricted-syntax: 2
    no-whitespace-before-property: 2
    no-underscore-dangle: 2
    no-unneeded-ternary: 2
    no-trailing-spaces: 2
    one-var:
        - 2
        - uninitialized: always
          initialized: never
    operator-assignment: 2
    operator-linebreak:
        - 2
        - after
        - overrides:
            ?: before
            ":": before
    padded-blocks:
        - 2
        - never
    quote-props: 
        - 2
        - as-needed
    require-jsdoc: 2
    semi-spacing: 2
    semi: 2
    sort-vars: 0
    sort-imports: 0
    space-in-parens: 2
    spaced-comment: 2
    wrap-regex: 2

    # ECMAScript 6
    arrow-body-style: 2
    arrow-parens: 2
    constructor-super: 2
    no-class-assign: 2
    no-confusing-arrow: 0
    no-const-assign: 2
    no-dupe-class-members: 2
    no-new-symbol: 2
    no-this-before-super: 2
    no-var: 2
    no-useless-constructor: 1
    object-shorthand: 2
    prefer-arrow-callback: 2
    prefer-const: 2
    prefer-reflect: 0
    prefer-rest-params: 2
    prefer-spread: 2
    require-yield: 2
    template-curly-spacing: 2
    yield-star-spacing: 2