---
extends: eslint:recommended
env:
    browser: true
    es6: true
    node: true
parserOptions:
    exmaVersion: 7
    sourceType: module
    ecmaFeatures:
        jsx: true
        restParams: true
        spread: true
        experimentalObjectRestSpread: true
plugins:
    - node
    - react
rules:
    # Possible Errors
    comma-dangle:
        - error
        - always-multiline
    no-console: warn
    no-unexpected-multiline: error
    valid-jsdoc:
        - error
        - requireReturn: false

    # Best Practices
    array-callback-return: error
    consistent-return: off
    block-scoped-var: error
    curly:
        - error
        - multi-line
    dot-location:
        - error
        - property
    dot-notation: error
    eqeqeq:
        - error
        - smart
    guard-for-in: error
    no-alert: warn
    no-caller: error
    no-case-declarations: error
    no-div-regex: error
    no-else-return: error
    no-empty-function:
        - error
        - allow:
            - arrowFunctions
    no-eval: warn
    no-extend-native: error
    no-extra-bind: error
    no-extra-label: error
    no-floating-decimal: error
    no-implicit-globals: error
    no-implied-eval: error
    no-invalid-this: off
    no-iterator: error
    no-labels: error
    no-lone-blocks: error
    no-loop-func: error
    no-magic-numbers: off
    no-multi-str: error
    no-native-reassign: error
    no-new-func: error
    no-new-wrappers: error
    no-new: error
    no-octal-escape: error
    no-param-reassign: error
    no-proto: error
    no-return-assign: error
    no-script-url: error
    no-self-compare: error
    no-sequences: error
    no-throw-literal: error
    no-unmodified-loop-condition: error
    no-unused-expressions: error
    no-useless-call: error
    no-useless-concat: error
    no-void: error
    no-warning-comments: warn
    no-with: error
    radix: error
    vars-on-top: error
    wrap-iife: error
    yoda: error

    # Strict Mode
    strict: error

    # Variables
    init-declarations: off
    no-catch-shadow: error
    no-label-var: error
    no-restricted-globals: error
    no-shadow-restricted-names: error
    no-shadow: off
    no-undef-init: error
    no-unused-vars:
        - 1
        - varsIgnorePattern: React
    no-use-before-define: error

    # Node.js and CommonJS
    callback-return: error
    global-require: warn
    handle-callback-err: error
    no-mixed-requires: error
    no-new-require: error
    no-path-concat: error
    no-process-exit: error
    no-sync: error

    # Stylistic Issues
    brace-style: error
    comma-style: error
    consistent-this: error
    jsx-quotes: error
    key-spacing: error
    keyword-spacing: error
    lines-around-comment: error
    max-depth: error
    max-len:
        - error
        - 80
        - 4
        - ignorePattern: "^\\s*[`'].*[`'][;,]?$"
    max-nested-callbacks: 
        - error
        - 3
    max-params: error
    max-statements: warn
    new-cap: off
    new-parens: error
    newline-after-var: off
    newline-before-return: error
    newline-per-chained-call:
        - error
        - ignoreChainWithDepth: 4
    no-array-constructor: error
    no-continue: error
    no-inline-comments: error
    no-lonely-if : error
    no-multiple-empty-lines: error
    no-nested-ternary: error
    no-new-object: error
    no-restricted-syntax: error
    no-whitespace-before-property: error
    no-underscore-dangle: error
    no-unneeded-ternary: error
    no-trailing-spaces: error
    one-var:
        - error
        - uninitialized: always
          initialized: never
    operator-assignment: error
    operator-linebreak:
        - error
        - after
        - overrides:
            ?: before
            ":": before
    padded-blocks:
        - error
        - never
    quote-props: 
        - error
        - as-needed
    require-jsdoc: error
    semi-spacing: error
    semi: error
    sort-vars: off
    sort-imports: off
    space-in-parens: error
    spaced-comment: error
    wrap-regex: error

    # ECMAScript 6
    arrow-body-style: error
    arrow-parens: error
    constructor-super: error
    no-class-assign: error
    no-confusing-arrow: off
    no-const-assign: error
    no-dupe-class-members: error
    no-new-symbol: error
    no-this-before-super: error
    no-var: error
    no-useless-constructor: warn
    object-shorthand: error
    prefer-arrow-callback: error
    prefer-const: error
    prefer-reflect: off
    prefer-rest-params: error
    prefer-spread: error
    require-yield: error
    template-curly-spacing: error
    yield-star-spacing: error

    #node
    node/no-missing-import: error
    node/no-missing-require: error
    node/no-unpublished-import: error
    node/no-unpublished-require: error
    node/no-unsupported-features: off
    node/shebang: error

    #React
    react/display-name: off
    react/forbid-prop-types:
        - error
        - forbid:
            - params
    react/no-danger: error
    react/no-deprecated: error
    react/no-did-mount-set-state: error
    react/no-did-update-set-state: error
    react/no-direct-mutation-state: error
    react/no-is-mounted: error
    react/no-multi-comp:
        - error
        - ignoreStateless: true
    react/no-set-state: off
    react/no-string-refs: error
    react/no-unknown-property: error
    react/prefer-es6-class: error
    react/prop-types: error
    react/react-in-jsx-scope: error
    react/require-extension: error
    react/self-closing-comp: error
    react/sort-comp: error
    react/sort-prop-types:
        - error
        - callbacksLast: true
          requiredFirst: true
    react/wrap-multilines: error

    #JSX-specific rules
    react/jsx-boolean-value: error
    react/jsx-closing-bracket-location: error
    react/jsx-curly-spacing: error
    react/jsx-equals-spacing: error
    react/jsx-handler-names: error
    react/jsx-indent-props: error
    react/jsx-indent: error
    react/jsx-key: error
    react/jsx-max-props-per-line:
        - error
        - maximum: 4
    react/jsx-no-bind:
        - error
        - allowArrowFunctions: true
    react/jsx-no-duplicate-props: error
    react/jsx-no-literals: off
    react/jsx-no-undef: error
    react/jsx-pascal-case: error
    react/jsx-sort-props:
        - error
        - callbacksLast: true
          shorthandFirst: true
    react/jsx-space-before-closing: error
    react/jsx-uses-react: error
    react/jsx-uses-vars: error
